// ****************************************************** //
// Generated by scripts\controls.py
// ****************************************************** //
#include "pch.h"
#include "_winui.h"

extern void add_runtimeclass_Microsoft_UI_Dispatching_DispatcherQueue(const py::module_ &m);
extern void add_callback_Microsoft_UI_Dispatching_DispatcherQueueHandler(const py::module_ &m);
extern void add_enum_Microsoft_UI_Dispatching_DispatcherQueuePriority(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Dispatching_DispatcherQueueTimer(const py::module_ &m);

PYBIND11_EMBEDDED_MODULE(_winui_Microsoft_UI_Dispatching, m) {
    add_runtimeclass_Microsoft_UI_Dispatching_DispatcherQueue(m);
    add_callback_Microsoft_UI_Dispatching_DispatcherQueueHandler(m);
    add_enum_Microsoft_UI_Dispatching_DispatcherQueuePriority(m);
    add_runtimeclass_Microsoft_UI_Dispatching_DispatcherQueueTimer(m);
}