// ****************************************************** //
// Generated by scripts\controls.py
// ****************************************************** //
#include "pch.h"
#include "_winui.h"

extern void add_struct_Windows_UI_Color(const py::module_ &m);

PYBIND11_EMBEDDED_MODULE(_winui_Windows_UI, m) {
    add_struct_Windows_UI_Color(m);
}