// ****************************************************** //
// Generated by scripts\controls.py
// ****************************************************** //
#include "pch.h"
#include "_winui.h"

void add_struct_Windows_UI_Color(const py::module_ &m) {
}

