// ****************************************************** //
// Generated by scripts\controls.py
// ****************************************************** //
#include "pch.h"
#include "_winui.h"

extern void add_enum_Microsoft_UI_Input_PointerDeviceType(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Input_PointerPoint(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Input_PointerPointProperties(const py::module_ &m);

PYBIND11_EMBEDDED_MODULE(_winui_Microsoft_UI_Input, m) {
    add_enum_Microsoft_UI_Input_PointerDeviceType(m);
    add_runtimeclass_Microsoft_UI_Input_PointerPoint(m);
    add_runtimeclass_Microsoft_UI_Input_PointerPointProperties(m);
}