// ****************************************************** //
// Generated by scripts\controls.py
// ****************************************************** //
#include "pch.h"
#include "_winui.h"

extern void add_struct_Windows_UI_Xaml_Interop_TypeName(const py::module_ &m);

PYBIND11_EMBEDDED_MODULE(_winui_Windows_UI_Xaml_Interop, m) {
    add_struct_Windows_UI_Xaml_Interop_TypeName(m);
}