// ****************************************************** //
// Generated by scripts\controls.py
// ****************************************************** //
#include "pch.h"
#include "_winui.h"
#include <winrt/Windows.System.h>

void add_enum_Windows_System_VirtualKeyModifiers(const py::module_ &m) {
    py::enum_<Windows::System::VirtualKeyModifiers>(m, "Windows.System.VirtualKeyModifiers")
        .value("None", Windows::System::VirtualKeyModifiers::None)
        .value("Control", Windows::System::VirtualKeyModifiers::Control)
        .value("Menu", Windows::System::VirtualKeyModifiers::Menu)
        .value("Shift", Windows::System::VirtualKeyModifiers::Shift)
        .value("Windows", Windows::System::VirtualKeyModifiers::Windows)
    ;
}

