// ****************************************************** //
// Generated by scripts\controls.py
// ****************************************************** //
#include "pch.h"
#include "_winui.h"

extern void add_enum_Microsoft_UI_Xaml_Visibility(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_BringIntoViewOptions(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_BringIntoViewRequestedEventArgs(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_DataContextChangedEventArgs(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_DependencyObject(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_DependencyProperty(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_DependencyPropertyChangedEventArgs(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_DragEventArgs(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_DragStartingEventArgs(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_DropCompletedEventArgs(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_EffectiveViewportChangedEventArgs(const py::module_ &m);
extern void add_enum_Microsoft_UI_Xaml_ElementSoundMode(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_ExceptionRoutedEventArgs(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_FrameworkElement(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_RoutedEventArgs(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_UIElement(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_Window(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_WindowEventArgs(const py::module_ &m);

PYBIND11_EMBEDDED_MODULE(_winui_Microsoft_UI_Xaml, m) {
    add_enum_Microsoft_UI_Xaml_Visibility(m);
    add_runtimeclass_Microsoft_UI_Xaml_BringIntoViewOptions(m);
    add_runtimeclass_Microsoft_UI_Xaml_BringIntoViewRequestedEventArgs(m);
    add_runtimeclass_Microsoft_UI_Xaml_DataContextChangedEventArgs(m);
    add_runtimeclass_Microsoft_UI_Xaml_DependencyObject(m);
    add_runtimeclass_Microsoft_UI_Xaml_DependencyProperty(m);
    add_runtimeclass_Microsoft_UI_Xaml_DependencyPropertyChangedEventArgs(m);
    add_runtimeclass_Microsoft_UI_Xaml_DragEventArgs(m);
    add_runtimeclass_Microsoft_UI_Xaml_DragStartingEventArgs(m);
    add_runtimeclass_Microsoft_UI_Xaml_DropCompletedEventArgs(m);
    add_runtimeclass_Microsoft_UI_Xaml_EffectiveViewportChangedEventArgs(m);
    add_enum_Microsoft_UI_Xaml_ElementSoundMode(m);
    add_runtimeclass_Microsoft_UI_Xaml_ExceptionRoutedEventArgs(m);
    add_runtimeclass_Microsoft_UI_Xaml_FrameworkElement(m);
    add_runtimeclass_Microsoft_UI_Xaml_RoutedEventArgs(m);
    add_runtimeclass_Microsoft_UI_Xaml_UIElement(m);
    add_runtimeclass_Microsoft_UI_Xaml_Window(m);
    add_runtimeclass_Microsoft_UI_Xaml_WindowEventArgs(m);
}