// ****************************************************** //
// Generated by scripts\controls.py
// ****************************************************** //
#include "pch.h"
#include "_winui.h"

extern void add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_ButtonBase(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_DragCompletedEventArgs(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_DragDeltaEventArgs(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_DragStartedEventArgs(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_FlyoutBase(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_FlyoutBaseClosingEventArgs(const py::module_ &m);
extern void add_enum_Microsoft_UI_Xaml_Controls_Primitives_FlyoutPlacementMode(const py::module_ &m);
extern void add_enum_Microsoft_UI_Xaml_Controls_Primitives_FlyoutShowMode(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_FlyoutShowOptions(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_LoopingSelector(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_RangeBase(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_ScrollBar(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_ScrollEventArgs(const py::module_ &m);
extern void add_enum_Microsoft_UI_Xaml_Controls_Primitives_ScrollEventType(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_Selector(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_SelectorItem(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_Thumb(const py::module_ &m);
extern void add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_ToggleButton(const py::module_ &m);

PYBIND11_EMBEDDED_MODULE(_winui_Microsoft_UI_Xaml_Controls_Primitives, m) {
    add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_ButtonBase(m);
    add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_DragCompletedEventArgs(m);
    add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_DragDeltaEventArgs(m);
    add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_DragStartedEventArgs(m);
    add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_FlyoutBase(m);
    add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_FlyoutBaseClosingEventArgs(m);
    add_enum_Microsoft_UI_Xaml_Controls_Primitives_FlyoutPlacementMode(m);
    add_enum_Microsoft_UI_Xaml_Controls_Primitives_FlyoutShowMode(m);
    add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_FlyoutShowOptions(m);
    add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_LoopingSelector(m);
    add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_RangeBase(m);
    add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_ScrollBar(m);
    add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_ScrollEventArgs(m);
    add_enum_Microsoft_UI_Xaml_Controls_Primitives_ScrollEventType(m);
    add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_Selector(m);
    add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_SelectorItem(m);
    add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_Thumb(m);
    add_runtimeclass_Microsoft_UI_Xaml_Controls_Primitives_ToggleButton(m);
}