// ****************************************************** //
// Generated by scripts\controls.py
// ****************************************************** //
#include "pch.h"
#include "_winui.h"

extern void add_runtimeclass_Microsoft_UI_Xaml_Media_MediaTransportControlsThumbnailRequestedEventArgs(const py::module_ &m);

PYBIND11_EMBEDDED_MODULE(_winui_Microsoft_UI_Xaml_Media, m) {
    add_runtimeclass_Microsoft_UI_Xaml_Media_MediaTransportControlsThumbnailRequestedEventArgs(m);
}