// ****************************************************** //
// Generated by scripts\controls.py
// ****************************************************** //
#include "pch.h"
#include "_winui.h"
#include <winrt/Microsoft.UI.Input.h>

void add_enum_Microsoft_UI_Input_PointerDeviceType(const py::module_ &m) {
    py::enum_<Microsoft::UI::Input::PointerDeviceType>(m, "Microsoft.UI.Input.PointerDeviceType")
        .value("Touch", Microsoft::UI::Input::PointerDeviceType::Touch)
        .value("Pen", Microsoft::UI::Input::PointerDeviceType::Pen)
        .value("Mouse", Microsoft::UI::Input::PointerDeviceType::Mouse)
        .value("Touchpad", Microsoft::UI::Input::PointerDeviceType::Touchpad)
    ;
}

void add_runtimeclass_Microsoft_UI_Input_PointerPoint(const py::module_ &m) {
    py::class_<Microsoft::UI::Input::PointerPoint, ::pywinui::holder<Microsoft::UI::Input::PointerPoint>, Windows::Foundation::IInspectable>(m, "Microsoft.UI.Input.PointerPoint")
        .def(py::init([](const ::winrt::Windows::Foundation::IInspectable &unk) { return ::pywinui::hold(unk.as<Microsoft::UI::Input::PointerPoint>()); }))
        .def("__repr__", [](typename cvt<Microsoft::UI::Input::PointerPoint>::cself_t _self) { return cvt<Microsoft::UI::Input::PointerPoint>(_self).repr(); })
        .def_property_readonly("FrameId", [](typename cvt<Microsoft::UI::Input::PointerPoint>::cself_t _self) { return cvt_out(_self.FrameId()); })
        .def_property_readonly("IsInContact", [](typename cvt<Microsoft::UI::Input::PointerPoint>::cself_t _self) { return cvt_out(_self.IsInContact()); })
        .def_property_readonly("PointerDeviceType", [](typename cvt<Microsoft::UI::Input::PointerPoint>::cself_t _self) { return cvt_out(_self.PointerDeviceType()); })
        .def_property_readonly("PointerId", [](typename cvt<Microsoft::UI::Input::PointerPoint>::cself_t _self) { return cvt_out(_self.PointerId()); })
        .def_property_readonly("Position", [](typename cvt<Microsoft::UI::Input::PointerPoint>::cself_t _self) { return cvt_out(_self.Position()); })
        .def_property_readonly("Properties", [](typename cvt<Microsoft::UI::Input::PointerPoint>::cself_t _self) { return cvt_out(_self.Properties()); })
        .def_property_readonly("Timestamp", [](typename cvt<Microsoft::UI::Input::PointerPoint>::cself_t _self) { return cvt_out(_self.Timestamp()); })
    ;
}

void add_runtimeclass_Microsoft_UI_Input_PointerPointProperties(const py::module_ &m) {
    py::class_<Microsoft::UI::Input::PointerPointProperties, ::pywinui::holder<Microsoft::UI::Input::PointerPointProperties>, Windows::Foundation::IInspectable>(m, "Microsoft.UI.Input.PointerPointProperties")
        .def(py::init([](const ::winrt::Windows::Foundation::IInspectable &unk) { return ::pywinui::hold(unk.as<Microsoft::UI::Input::PointerPointProperties>()); }))
        .def("__repr__", [](typename cvt<Microsoft::UI::Input::PointerPointProperties>::cself_t _self) { return cvt<Microsoft::UI::Input::PointerPointProperties>(_self).repr(); })
    ;
}

