// ****************************************************** //
// Generated by scripts\controls.py
// ****************************************************** //
#include "pch.h"
#include "_winui.h"

extern void add_enum_Windows_ApplicationModel_DataTransfer_DataPackageOperation(const py::module_ &m);
extern void add_runtimeclass_Windows_ApplicationModel_DataTransfer_DataPackage(const py::module_ &m);

PYBIND11_EMBEDDED_MODULE(_winui_Windows_ApplicationModel_DataTransfer, m) {
    add_enum_Windows_ApplicationModel_DataTransfer_DataPackageOperation(m);
    add_runtimeclass_Windows_ApplicationModel_DataTransfer_DataPackage(m);
}